version: "3.8"

services:
  partnerbot:
    build: .
    container_name: partnerbot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GOOGLE_CREDS_RAW=${GOOGLE_CREDS_RAW}
      - SHEET_ID=${SHEET_ID}
      - SOURCE_CHANNEL_ID=${SOURCE_CHANNEL_ID}
    command: python main.py
    restart: unless-stopped
